### ISSUE TITLE
Interiorid & VirtualWorld

### ISSUE THREAD

**Issue by PatchwerkQWER** [Pottus/Texture-Studio#13]
Hi,

I think this will be really useful. Should you add VirtualWorld and Interiorid parameter in export? But let it as string. Because I love readability. So I have maps with interoir in define for easy way to change it like `#define BANK_INT 30` or `#define EVENT_VW 11`.

Cheers

**Comment by Pottus** [comment]
You could certainly modify it afterwards fairly easily. My best thought would be to create a more in depth export dialog for all the settings but don't think I would really get around to doing it but Crayder might. It's probably only a couple hours work I would think.

**Comment by Crayder** [comment]
Modifying the output afterwards is extremely simple. If I were to do this I don't think I would use defines, I'd like to keep it relatively simple for the newbies and such. This is a bit extensive though, not that I won't consider it. Instead of a "more in depth export dialog" I'd rather just add one more dialog asking whether to use the player's current virtual world and interior. That way it's more easily understood.

**Comment by Pottus** [comment]
Well you could update the map format to have a map data table to extend the data stored by the map. This is the route I would take if you look at tsmain.pwn and check out the sqlite_UpdateDB() you will see it is very easy to update the map format with just a couple queries.

**Comment by Crayder** [comment]
Done on the inprogress branch, untested
