### ISSUE TITLE
/avnewcar parameters

### ISSUE THREAD

**Issue by JustMe77** [Pottus/Texture-Studio#33]
The list of the vehicles must be split in 2 ore more, because the list end at id 540.
That means you cant create any vehicle above id 540..

**Comment by Crayder** [comment]
Ok...

- VehicleList is the string that accommodates the entire list of vehicle names and ID's. The names themselves total up 1619 characters. Then there are the ID's which take up less than 1484 characters ((2 paranthesis + 3 digits + 1 space + 1 newline) * 212 vehicles). VehicleList's size is 4096 so 3103 possible characters are not the problem.
- The loop that sets the string loops through all of the vehicles, so that's not the problem.
- Couldn't be a YSI's y_dialogs since it just wraps the normal ShowPlayerDialog function, which can definitely support 4096 characters.

I honestly don't know what I'm missing. It's probably something super simple I'm over looking.
@Pottus anything?

**Comment by Pottus** [comment]
Let me see here.

**Comment by JustMe77** [comment]
Here is a Screenshot. Anyways, why not making it simple and do it like /avnewcar <vehicle name/id> ?
It's much better, I need like 3 minutes till I found my vehicle in the dialog list..

http://imgur.com/Desz5Oy

**Comment by Crayder** [comment]
I'll make it so it takes an optional parameter. In no Paramus are provided the list will be shown.
