### ISSUE TITLE
AMX Backtrace: "Heap underflow"

### ISSUE THREAD

**Issue by KnowNN** [Pottus/Texture-Studio#38]
Hi, I found a mistake with this filterscript, when I open the server on 0.3.7, the console say following error:

```
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x262FE44
```

Because this, the commands don't work ("SERVER: Unknown error.").
However, sometimes this debug don't appear, but when i join the server, the console spamming this AMX Backtrace.

**Comment by Crayder** [comment]
Have you done anything to the source? Did you use a blank gamemode?

Try downloading TS then ONLY add samp-server.exe to the extracted files (that's all you need to run TS).

**Comment by KnowNN** [comment]
I tried exactly you said before reported this problem.

**Comment by Crayder** [comment]
Well, I've never seen this problem or even heard of it happening with TS.

I don't have a clue on how to help you without some more insight on what you've done. A completely clean package with no re-compiling or anything at all should run smooth as butter.

**Comment by KnowNN** [comment]
Is clean package, with samp-server.exe downloaded from sa-mp.com. If you want, you can add "#pragma dynamic 15000" for me.

**Comment by Crayder** [comment]
No, I definitely don't want to do that. That's not a fix. In fact, if you added that you'd probably cause more problems.

**Comment by KnowNN** [comment]
So, any solution?

**Comment by Crayder** [comment]
No, there is no solution that I can come up with. It's a problem only YOU are having.

**Comment by KaizerHind** [comment]
**English:**
The problem is unknown.
Apparently if you block your connection, or `if you specifically block the connection to TextureStudio, you can run it just fine`.
On the other hand, a user in the OpenMP community shared the following TS with recent includes and it works without problem.

**Credits: edgyaf#4961**

**Download:**
[Download Texture Studio 1.9](https://cdn.discordapp.com/attachments/231799180127895553/1096196372937576478/Texture-Studio.zip)

**Español:**
El problema se desconoce.
Aparentemente si bloqueas tu conexion o bien, `si bloqueas la conexion especificamente a TextureStudio, puedes ejecutarlo sin problemas.`
Por otro lado, un usuario en el Discord de OpenMP, me compartio el siguiente TS con los includes recientes y funciona sin problema. 

**Creditos: edgyaf#4961**

**Descarga:**
[Descargar Texture Studio 1.9](https://cdn.discordapp.com/attachments/231799180127895553/1096196372937576478/Texture-Studio.zip)

**Comment by Mobinbaratian13** [comment]
Hi everyone,

I recently encountered the "Heap Underflow" issue with Texture Studio 1.9d, and I managed to find a solution that worked for me. I thought I'd share it here to help others who may be facing the same problem.

I followed these steps:


1. Downloaded the samp_server_r2.zip file from the official SA-MP website : 
[SA-MP San Andreas Multiplayer](https://www.sa-mp.com/download.php) Or Server File Direct Link [SA-MP 0.3.7-R2 Windows Server](http://files.sa-mp.com/samp037_svr_R2-1-1_win32.zip)
2. Extract the SA-MP server files, including an empty gamemode and any necessary configurations.
3. Download the Texture Studio files from the GitHub repository: [Texture Studio GitHub](https://github.com/Pottus/Texture-Studio) Or The TD Files Direct Link [Texture-Studio-master.zip](https://github.com/Pottus/Texture-Studio/archive/refs/heads/master.zip)
4. Extract the Texture Studio files.
5. Merge the Texture Studio files with the SA-MP server files, replacing any conflicting files.

After following these steps, the issue was resolved, and I was able to run the Texture Studio server successfully. I hope this solution works for you as well.

Feel free to ask if you have any further questions. Good luck!

Best regards,
[ғᴀɪʀʏᴛʟᴀᴇs ˢʰᵃᵈᵒʷ](https://t.me/fairytalesShadow)
