### ISSUE TITLE
1.9 Test Results

### ISSUE THREAD

**Issue by JustMe77** [Pottus/Texture-Studio#51]
Hi, I'll mention things here which are NOT working, which mean all other things I've tested were working fine.

Note command:
- What is the use of this command? I thought it's to add a note for every object you create, if this is the case, then it's not working properly. I've created 2 Objects: 19377 & 19372. I've set a note on 19377 Index 0 Hello, and if I set another note on 19372 Object, the other note gets replaced. So it mean, you can have maximum 1 note for all Objects..
- /setspawn & gotomap are working, but it's not saving. It should save obviously..
- Default server commands are not working if tstudio is loaded - please fix.
- Server crashed when I've tried to repeat command with holding ALT and pressing Crouch
  Crash Information:

[22:06:15]   Filterscript 'tstudio.amx' loaded.
[22:06:16] [chat] [[LnD]JustMe.77]: t
[22:06:30] [debug] Server crashed while executing tstudio.amx
[22:06:30] [debug] AMX backtrace:
[22:06:30] [debug] #0 00000014 in public OnPlayerKeyStateChange () from tstudio.amx
[22:06:31] [debug] Native backtrace:
[22:06:31] [debug] #0 6df88028 in ?? () from plugins\crashdetect.DLL
[22:06:31] [debug] #1 6df809c7 in ?? () from plugins\crashdetect.DLL
[22:06:31] [debug] #2 6df8631a in ?? () from plugins\crashdetect.DLL
[22:06:31] [debug] #3 0fed2930 in ?? () from plugins\YSF.DLL
[22:06:31] [debug] #4 0046b6c8 in ?? () from samp-server.exe
[22:06:31] [debug] #5 004837a5 in ?? () from samp-server.exe
- /avsiren is working, but you can't toggle siren even it's saying it has been toggled.
- Old Maps are loading, but with completely wrong textures (I hope my map is not fucked up)

**Comment by Crayder** [comment]
>/avsiren is working, but you can't toggle siren even it's saying it has been toggled.
It IS being toggled, but the vehicle needs respawned or whatever.

------------------------

>I hope my map is not fucked up
Obviously you should've backed up your maps before loading them in a beta version... xD

---------------------

I've thoroughly tested the notes and the spawns (even the saving and loading of both), they both worked perfectly for me.

------------------------

>Default server commands are not working if tstudio is loaded - please fix.

I use fsdebug alongside TS1.9 fine, not sure about GM CMDS.

-------------------------

>Server crashed when I've tried to repeat command with holding ALT and pressing Crouch

That is part of the new command buffer. Alt+C should repeat the last command. The crash may be caused by having multiple YCMD scripts, are you running a different gamemode or additional filterscripts? Either that or maybe you just haven't input any commands yet. I haven't tested it yet myself but the code looks clean. https://github.com/Pottus/Texture-Studio/blob/inprogress/filterscripts/tstudio/cmdbuffer.pwn

**Comment by JustMe77** [comment]
> It IS being toggled, but the vehicle needs respawned or whatever.

Didn't test it. I'll try that out. But why not just respawning it automaticly if you enable / disable siren and put the player back in the vehicle?

> Obviously you should've backed up your maps before loading them in a beta version... xD

I havn't done that, but no problem.

> I've thoroughly tested the notes and the spawns (even the saving and loading of both), they both worked perfectly for me.

About what spawns you're talking? Could you maybe explain in detail what the note command is for? I may mistunderstood the use of it.

> I use fsdebug alongside TS1.9 fine, not sure about GM CMDS.

I'm not using fsdebug, but a few other filterscripts. It was everything working fine with the old version..


> That is part of the new command buffer. Alt+C should repeat the last command. The crash may be caused by having multiple YCMD scripts, are you running a different gamemode or additional filterscripts? Either that or maybe you just haven't input any commands yet. I haven't tested it yet myself but the code looks clean. 

I'm using ZCMD in my gamemode / filterscripts. Yes, I use a different gamemode and a few Filterscripts.

**Comment by Crayder** [comment]
>>I use fsdebug alongside TS1.9 fine, not sure about GM CMDS.

>I'm not using fsdebug, but a few other filterscripts. It was everything working fine with the old version..

>>That is part of the new command buffer. Alt+C should repeat the last command. The crash may be caused by having multiple YCMD scripts, are you running a different gamemode or additional filterscripts? Either that or maybe you just haven't input any commands yet. I haven't tested it yet myself but the code looks clean.

>I'm using ZCMD in my gamemode / filterscripts. Yes, I use a different gamemode and a few Filterscripts.

The problem with that is the Command_ReProcess. It reprocesses the last command. If that command isn't from TS/YCMD it may have a weird reaction, thus the crash. It's not my or Y_Less's fault, it's a PAWN thing and the way multiple command processors are handling commands together.

fsdebug doesn't have this problem because it is using the old generic, shit-ball strcmp... I don't recommend that as an alternative.

>About what spawns you're talking?

The `/setspawn` and `/gotomap`. You said they don't save, when I know for sure they did when I tested.

>Could you maybe explain in detail what the note command is for? I may mistunderstood the use of it.

They are literally just that, notes. That is their purpose. They can help you sort objects and tell you which ones are which. They are like labels.

They can be shown in the 3D text with the new 3D text options command, see `/thelp` for that. They are also exported as comments (Yes, PAWN comments) on the objects too, which I also tested and verified.
