### ISSUE TITLE
/showtext3d [radius]

### ISSUE THREAD

**Issue by musa11971** [Pottus/Texture-Studio#52]
Would be very useful to only show 3dtext in a certain radius. If parameter is not defined, then just show all 3dtext.

**Comment by JustMe77** [comment]
I agree, I've suggested this already ages ago when Pottus was maintaining it (I guess) 💃

**Comment by Crayder** [comment]
I was already adding this when I thought a multiplier might be more useful than a set distance.

https://github.com/Pottus/Texture-Studio/blob/aae8d4c2043cd5550166237635fcd3d6d48f8630/filterscripts/tstudio/tsmain.pwn#L4681

The multiplier feature was bugged in streamer at the time. Now that it's fixed in streamer I'll try again.

**Comment by musa11971** [comment]
More than a year later and I'm still eager for this feature to be added. I still have hope!

**Comment by musa11971** [comment]
More than two years later and I'm still eager for this feature to be added. I still have hope!
