### ISSUE TITLE
Raise the max streamed in objects' amount

### ISSUE THREAD

**Issue by wtfrazr** [Pottus/Texture-Studio#65]
Hey.
Right now it is only at 500, what the server can show to a player at a time. So if you have a map that is above 500 objects, when you move around, the objects disappear/appear, as they stream in.
I think it should be raised to 2000, since the 0.3.DL (and 0.3.8) allows that to be streamed in at one time.

**Comment by Crayder** [comment]
If you want to raise the max for your personal TS, go ahead. It's set low for a reason. The max objects is 1000 in the main release branch. TS isn't designed for DL yet.

Keep in mind, if you raise that limit and create a lot of objects in one area (for example, using /obmedit) you risk constantly being kicked from the server because of the ackslimit. You can raise the ackslimit in the server.cfg. If you have great internet and a good PC it is perfectly fine to set both the ackslimit and the max objects well above 500. TS is meant to be able to run for ALL users though.

**Comment by Crayder** [comment]
I'm just going to make it automatically check if you are using 0.3.8 RC1 (the first DL version, adds AddSimpleModel) or higher. It'll automatically raise the maximum streamer objects to 1500, SA-MP does the rest itself.
