### ISSUE TITLE
Issuse solution found 

### ISSUE THREAD

**Issue by HyeN2018** [Pottus/Texture-Studio#96]
https://github.com/Pottus/Texture-Studio/issues/38
Hey , dou u remember this issuse ? I attempted this issuse 1 day ago but now i found the solution , its very easy , just change the directory of your server .
I hope i helped you !

**Comment by HyeN2018** [comment]
https://github.com/Pottus/Texture-Studio/issues/38

**Comment by Crayder** [comment]
You could've just commented there, and also explain a little more. I'm not even sure what you mean by that.

**Comment by AnthonyJuan** [comment]
I'm having the same problem, could it be more specific to help me?

**Comment by KaizerHind** [comment]
**English:**
If anyone has the same error at any time, please download this.
I don't remember what I did exactly, the only changes were to `change the name of the folder`, `remove a couple of values that I had in server.cfg` and `re-add the filterscripts and gamemodes files`.

**Español:**
Si alguien presenta el mismo error en alguna ocasion, obten por descargar esto.
No recuerdo que hice exactamente, los unicos cambios que fue `cambiar el nombre a la carpeta`, r`etirar un par de valores que tenia en server.cfg` y `volver a añadir los archivos de filterscripts y gamemodes`.

**Download:**
https://cdn.discordapp.com/attachments/947367217287270421/1095867279813656636/TextureStudio_1.9.rar
https://cdn.discordapp.com/attachments/947367217287270421/1095867434361176174/pawno.rar

**Comment by santrus07** [comment]
> Estoy teniendo el mismo problema, ¿podría ser más específico para ayudarme?

Out of nowhere the same thing began to happen, I also don't think they respond.

**Comment by KaizerHind** [comment]
**English:**
The problem is unknown.
Apparently if you block your connection, or `if you specifically block the connection to TextureStudio, you can run it just fine`.
On the other hand, a user in the OpenMP community shared the following TS with recent includes and it works without problem.

**Credits: edgyaf#4961**

**Download:**
[Download Texture Studio 1.9](https://cdn.discordapp.com/attachments/231799180127895553/1096196372937576478/Texture-Studio.zip)

**Español:**
El problema se desconoce.
Aparentemente si bloqueas tu conexion o bien, `si bloqueas la conexion especificamente a TextureStudio, puedes ejecutarlo sin problemas.`
Por otro lado, un usuario en el Discord de OpenMP, me compartio el siguiente TS con los includes recientes y funciona sin problema. 

**Creditos: edgyaf#4961**

**Descarga:**
[Descargar Texture Studio 1.9](https://cdn.discordapp.com/attachments/231799180127895553/1096196372937576478/Texture-Studio.zip)

**Comment by KaizerHind** [comment]
> > Estoy teniendo el mismo problema, ¿podría ser más específico para ayudarme?
> 
> Out of nowhere the same thing began to happen, I also don't think they respond.

**English:**
The problem is unknown.
Apparently if you block your connection, or `if you specifically block the connection to TextureStudio, you can run it just fine`.
On the other hand, a user in the OpenMP community shared the following TS with recent includes and it works without problem.

**Credits: edgyaf#4961**

**Download:**
[Download Texture Studio 1.9](https://cdn.discordapp.com/attachments/231799180127895553/1096196372937576478/Texture-Studio.zip)

**Español:**
El problema se desconoce.
Aparentemente si bloqueas tu conexion o bien, `si bloqueas la conexion especificamente a TextureStudio, puedes ejecutarlo sin problemas.`
Por otro lado, un usuario en el Discord de OpenMP, me compartio el siguiente TS con los includes recientes y funciona sin problema. 

**Creditos: edgyaf#4961**

**Descarga:**
[Descargar Texture Studio 1.9](https://cdn.discordapp.com/attachments/231799180127895553/1096196372937576478/Texture-Studio.zip)
